# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5ad120fd1f7bfb8ac6acaf818ceb8ee47da3a57713cfd031045bcd6fcf8758f07f383def01a390e13d6a38ad9f663c7796896739fafe93f131095cb1693465

test:
  secret_key_base: 5edd195cb94b1c6995b9785947d13a6b0831657334a85441c5e22697fe0286c5c26af7c9e6b3cf8d0bbec1b9342b5a8dfb696b250c3c71d2a45397504172f9bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
